In [1]:
import numpy as np

In [5]:
#Crear un vector de ceros de tamaño 10
arreglo = np.zeros([10])
arreglo

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
#Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1
arreglo = np.zeros([10])
arreglo[5]=1
arreglo

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [12]:
#Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc
arreglo = np.arange(50)
arreglo = arreglo3[::-1]
arreglo

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [21]:
#Crear una matriz de 3 x 3 con valores del cero al 8
arreglo = np.arange(9).reshape(3,3)
arreglo

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [26]:
#Encontrar los indices que no sean cero en un arreglo
arreglo = np.array([1,2,0,0,4,0])
np.where(arreglo == 0)


(array([2, 3, 5], dtype=int64),)

In [30]:
#Crear una matriz de identidad 3 x 3

arreglo = np.eye(3)
arreglo

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
#Crear una matriz 3 x 3 x 3 con valores randomicos
arreglo = np.random.rand(3,3,3)
arreglo

array([[[0.54954285, 0.92193683, 0.08844276],
        [0.04223631, 0.10998593, 0.74871665],
        [0.22262637, 0.81455299, 0.60676806]],

       [[0.17880458, 0.36813759, 0.82871072],
        [0.63301083, 0.69861985, 0.03451275],
        [0.22632655, 0.03530988, 0.53839062]],

       [[0.9025403 , 0.9731075 , 0.81756714],
        [0.91577432, 0.00332215, 0.73106031],
        [0.54142652, 0.09445961, 0.58132423]]])

In [50]:
#Crear una matriz 10 x 10 y encontrar el mayor y el menor
arreglo = np.random.randint(0,100,(10,10))
menor = arreglo.min()
mayor = arreglo.max()
print(menor)
print(mayor)
arreglo


1
99


array([[30, 36, 60,  3, 50, 18, 69, 82, 69, 47],
       [68, 90, 37, 89, 26, 82, 67, 64, 18, 41],
       [10, 79, 22, 82, 60, 68, 99, 25, 96, 72],
       [35, 44, 21, 42, 92, 48, 60, 43, 11,  6],
       [ 2,  2, 68, 67, 14, 62, 76, 46, 51,  1],
       [90, 33, 33, 38, 11, 45, 74, 84, 77, 87],
       [32, 27, 43, 35, 47, 60, 72, 28, 57, 17],
       [11, 27, 28, 93, 82, 14, 82, 87, 25, 21],
       [70, 70, 66, 14, 36, 41, 13, 93, 20, 93],
       [90, 32, 45, 94, 81, 19, 91, 53, 25, 73]])

In [ ]:
#Sacar los colores RGB unicos en una imagen
from scipy import ndimage
from scipy import misc
import matplotlib.pyplot as plt
mpache = misc.face()
plt.imshow(mpache)


In [54]:
#¿Como crear una serie de una lista, diccionario o arreglo?
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
serie_lista=pd.Series(mylist)
serie_arreglo=pd.Series(myarr)
serie_dict=pd.Series(mydict)

print(serie_lista)
print(serie_arreglo)
print(serie_dict)



0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64


In [60]:
#Como convertir el indice de una serie en una columna de un DataFrame?
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict) 
# Transformar la serie en dataframe y hacer una columna indice
df1 = pd.DataFrame(myarr)


In [120]:
#¿Como obtener los items que esten en una serie A y no en una serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

res = ser1.isin(pd.to_numeric(ser2))
res

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [84]:
#¿Como obtener los items que no son comunes en una serie A y serie B?
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
serconcat = pd.concat([ser1,ser2] )
serconcat

0    1
1    2
2    3
3    4
4    5
0    4
1    5
2    6
3    7
4    8
dtype: int64

In [96]:
#Como obtener el numero de veces que se repite un valor en una serie
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
ser.value_counts()



c    6
h    6
d    5
b    4
a    3
e    3
f    2
g    1
dtype: int64

In [97]:
#¿Como mantener los 2 valores mas repetidos de una serie, y a los demas valores cambiarles por 0 ?
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
