In [1]:
#pip install numpy
import numpy as np

In [4]:
print(type([1,2,3]))
print(type((1,2,3)))
print(type(np.array([1,2,3])))
print(type(np.array((1,2,3))))


<class 'list'>
<class 'tuple'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
np.zeros([5,7,2])

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
#np.zeros((5,3))
np.ones((5,2))


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
#np.arange(120)
#np.arange(4,20)
np.arange(-12,-10)

array([-12, -11])

In [35]:
np.arange(-12,0,0.5)

array([-12. , -11.5, -11. , -10.5, -10. ,  -9.5,  -9. ,  -8.5,  -8. ,
        -7.5,  -7. ,  -6.5,  -6. ,  -5.5,  -5. ,  -4.5,  -4. ,  -3.5,
        -3. ,  -2.5,  -2. ,  -1.5,  -1. ,  -0.5])

In [39]:
arreglo_pares = np.arange(0,20,2)



In [40]:
print(arreglo_pares.size)
print(len(arreglo_pares))

10
10


In [42]:
arreglo_tres_dimensiones = np.zeros((2,3,4))
print(arreglo_tres_dimensiones.shape)

(2, 3, 4)


In [45]:
arreglo_pares.reshape(5,2)

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [51]:
arreglo_de_vc = np.arange(24)
arreglo_de_vc.reshape(4,6) #2*12,12*2,6*4,4*6,24*1, 2*2*2*3, 8*3,3*8

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [50]:
a = np.array([10,10,10])
b = np.array([5,5,5])

In [57]:
#a+b
#a-b
#a*b
a/b


array([2., 2., 2.])

In [107]:
arreglo_test=np.array([1,2,3,4,6,7,8,6,40,20,5,4]).reshape(3,2,2)
arreglo_test2=np.array([3,2,3,5,6,0,8,6,6,20,5,1]).reshape(3,2,2)


In [97]:
arreglo_test+arreglo_test2

array([[[ 4,  4],
        [ 6,  9]],

       [[12,  7],
        [16, 12]],

       [[46, 40],
        [10,  5]]])

In [99]:
arreglo_test-arreglo_test2

array([[[-2,  0],
        [ 0, -1]],

       [[ 0,  7],
        [ 0,  0]],

       [[34,  0],
        [ 0,  3]]])

In [101]:
arreglo_test*3
arreglo_test/2

array([[[ 0.5,  1. ],
        [ 1.5,  2. ]],

       [[ 3. ,  3.5],
        [ 4. ,  3. ]],

       [[20. , 10. ],
        [ 2.5,  2. ]]])

In [112]:
arreglo_muestra = np.arange(20).reshape(5,2,2)


In [123]:
respuesta = arreglo_muestra >3
respuesta2 = arreglo_muestra <10

In [126]:
arreglo_muestra[respuesta*respuesta2]

array([4, 5, 6, 7, 8, 9])

In [129]:
arreglo_muestra[(arreglo_muestra >6)*(arreglo_muestra <14)*(arreglo_muestra%2==0)]

array([ 8, 10, 12])